version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: orest
      POSTGRES_PASSWORD: ffb73chb
      POSTGRES_DB: mydb
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 1GB
        reservations:
          cpus: "2"
          memory: 1GB
  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - 8077:8080
